In [46]:
img_in_python = [[12,34,123,456,12],[12,34,123,456,12],[12,34,123,456,12]] # Cada numero representa um pixel

In [47]:
import numpy

n = numpy.arange(27) # Quantidade de elementos
n.reshape(3, 3, 3) # Quantidade em cada dimensão, nesse caso são 3D

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
m = numpy.asarray([[12,34,123,456,12],[12,34,123,456,12],[12,34,123,456,12]])
m
# Parece igual ao anterior, mas agora não é um numpy array, é um list nativo do Python

array([[ 12,  34, 123, 456,  12],
       [ 12,  34, 123, 456,  12],
       [ 12,  34, 123, 456,  12]])

In [49]:
import cv2

img = cv2.imread('smallgray.png', 0) # 0 em grey scale, e 1 em BGR
print(img)

cv2.imwrite('new_samllgray.png', img) # cria uma nova imagem, retorna True se criou com sucesso

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


True

In [50]:
img = cv2.imread('smallgray.png', 0)
img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [51]:
print(img.shape)
print(img[2,4])
img[:, 2:4]

(3, 5)
182


array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [52]:
for i in img:
    print(i)
    
for i in img.T: # transposto
    print(i)

for i in img:
    for j in i:
        print(j)
        
print('----- OUTRO IGUAL -----')
for i in img.flat: # flat acessa valor por valor do img
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]
[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]
187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
----- OUTRO IGUAL -----
187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [53]:
imc = numpy.hstack((img,img)) # stacka horizontalmente dois arrays, passa uma tubla com os dois
imc # stackar horizontalmente é concatenar as tabelas pela direita

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [54]:
imv = numpy.vstack((img,img)) # stacka verticalmente dois arrays, passa uma tubla com os dois
imv # stackar verticalmente é concatenar as tabelas por baixo

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [55]:
lst = numpy.hsplit(img, 5) # divide o array na quantidade de arrays passada
lst # um array de cada coluna

[array([[187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182]], dtype=uint8)]

In [57]:
lsv = numpy.vsplit(img, 3) # divide o array na quantidade de arrays passada
lsv # um array de cada linha

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]